// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables (required, no fallback to stale hardcoded values)
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('⚠️ Supabase credentials not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables.');
}

console.log('✅ Supabase client initializing with URL:', SUPABASE_URL.substring(0, 30) + '...');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safely get localStorage only if in browser environment
const getStorage = () => {
  if (typeof window !== 'undefined' && typeof window.localStorage !== 'undefined') {
    return window.localStorage;
  }
  return undefined;
};

// NOTE: The auto-generated `Database` types only cover a subset of the live schema
// (tables like boqs, lcl_template_*, cash_receipts are missing). To unblock the
// build while the types regenerate, the client is cast to `any` here. Runtime
// behaviour is unchanged.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    storageKey: 'sb-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js/web',
    },
  },
}) as any;
